### PR TITLE
simplify github templates

### PR DESCRIPTION
**Pull request by MarcoIeni**
I feel like the issue template may be a little bit intimidating at first.
Maybe if you don't see a wall of text in the preview it is better.

Additionally, with comments we make it clearer that all that text should me not included in your final message, too.

### CODE REVIEW

**Comment by stevenguh** [comment]
I like it especially the removal of the checkboxes, because they are shown in the github as items needed to be finished.

**Comment by MarcoIeni** [comment]
Yes, that was really annoying :)

**Comment by stevenguh** [comment]
merge?

**Comment by MarcoIeni** [comment]
I will do it when I am at the laptop. So I will try them. After that I will solve #109

**Comment by MarcoIeni** [comment]
I close this, there's no need to merge this and delete the same files in the next commit.
I applied these changes to the [.github](https://github.com/VSpaceCode/.github) repo directly.

**Pull request closed without merging**
