### PR TITLE
Create Keybindings from package.json

### LINKED ISSUE #47: Create a markdown table from the default key bindings
Issue from https://github.com/stevenguh/spacecode/issues/9

> This idea is coming from https://github.com/stevenguh/spacecode/issues/8. It would be great to have a script in the prepublish step to generate a markdown table from the default bindings in the `package.json` to use in `README.md`. I am thinking this would generate a separate markdown file at the root directory like `KEYBINDINGS.md` then the `README.md` can refer to all the default key bindings we have.

### PR DESCRIPTION
**Pull request by stevenguh**
Fixes #47

### CODE REVIEW

**Comment by stevenguh** [comment]
@MarcoIeni I know you are making changes to keybindings, we probably will need to regenerate once you are done with the changes.

**Comment by MarcoIeni** [comment]
couldn't this be done in the CI on every push?
The markdown file could be stored on github pages branch.

**Comment by stevenguh** [comment]
Those are great ideas!! Do you have experience in those?

**Comment by MarcoIeni** [comment]
yes, if you write here the command you run on your machine I can do the github action (I am not a javascript developer as you may have noticed) ^^'

**Comment by stevenguh** [comment]
Run `npm run generate-keybindings` after `npm install` on a fresh clone should generate and override `KEYBINDINGS.md`.

**Comment by MarcoIeni** [comment]
Ok, I assigned this to myself. I will push the commits directly to this pull requests.

**Comment by stevenguh** [comment]
Thank you very much 💯

**Comment by MarcoIeni** [comment]
Done!
If you like it you can merge it, this should be the end result: https://github.com/MarcoIeni/VSpaceCode/tree/gh-pages

The gh-pages at the moment is used as a normal github branch, i.e. there is no website associated to it, so the file can be viewed normally by the github website (see the link in the README).

If someone in the future would like to do deploy a website from that branch, that file is already there :)

**Comment by stevenguh** [comment]
should we perform the action on tag like https://github.com/VSpaceCode/VSpaceCode/blob/master/.github/workflows/deploy.yml#L2-L4?

**Comment by MarcoIeni** [comment]
seems a good idea, I've changed it :+1:

**Comment by stevenguh** [comment]
Thanks for helping out. Merged.

**Pull request merged**
