### PR TITLE
add issue template

### PR DESCRIPTION
**Pull request by MarcoIeni**
the result should be similar to this: https://github.com/rust-github/template/issues/new/choose

### CODE REVIEW

**Comment by stevenguh** [comment]
Looks good :) btw should we have the same template on other repo of this org like `vscode-which-key`?

**Comment by MarcoIeni** [comment]
If you think they are useful yes. I added the templates in this one because I imagine that it would be the most used repo among the one of the organization.

**Comment by stevenguh** [comment]
Let's try that 🙂 Since there were quite a bit of feature requests on that repo as well

**Comment by MarcoIeni** [comment]
Ok, I will add it

**Comment by stevenguh** [comment]
Thanks a lot marco 😊

**Comment by MarcoIeni** [comment]
done [here](done here: https://github.com/VSpaceCode/vscode-which-key/commit/29477466949acdcda246d3d7cc6259a7799f9235)

**Pull request merged**
