### PR TITLE
README: move "Menu Customization" to website

### PR DESCRIPTION
**Pull request by MarcoIeni**
Temporarily, the section of the README points to the website. In the future, when the website is finished, the section will be removed.

### CODE REVIEW

**Comment by MarcoIeni** [comment]
@stevenguh by mistake I commited a change to the `master`.

In order to repair, I created this pull request, that adds that commit to the `develop` branch.
Is it ok as a solution? If not we can close this pull request and I will remove that commit from the master branch.

**Comment by stevenguh** [comment]
That sounds good. Force push to fix the master branch :)

**Comment by MarcoIeni** [comment]
ok, I will do it

**Comment by MarcoIeni** [comment]
Done. Maybe once we finish the website, we can remove the "develop" branch and we can develop directly on master. Releases will be done on tags, as usual.
In fact, once we have the website, I don't expect the README to change very often.

**Comment by stevenguh** [comment]
That makes sense and sounds good to me :)

**Comment by MarcoIeni** [comment]
I think that the website now is fine more or less. If you think something more has to be done to make it acceptable, please open an issue. Otherwise we can delete the develop branch once it is merged to master on both WhichKey and vspacecode.

**Comment by stevenguh** [comment]
Agree, and thank you. Reference: https://github.com/VSpaceCode/vspacecode.github.io/issues/1#issuecomment-695169116

**Pull request closed without merging**
