### PR TITLE
Add F# major mode

### PR DESCRIPTION
**Pull request by sleepyfran**
This PR adds support for the F# mode via Ionide, therefore it assumes that the [Ionide F#](https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp) extension is installed.

The added keybindings are rather generic and available through VSCode commands, these are:

## Go to
- Go to definition (with both <kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>d</kbd> and <kbd>SPC</kbd> <kbd>g</kbd> <kbd>g</kbd>)
- Go to errors (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>e</kbd>)
- Find symbol in file (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>i</kbd>)
- Peek references (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>r</kbd>)
- Peek definition (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>D</kbd>)
- Find symbol in project (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>I</kbd>)
- Find all references (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>g</kbd> <kbd>R</kbd>)

## Format
- Format region or buffer (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>=</kbd> <kbd>=</kbd>)
- Format buffer (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>=</kbd> <kbd>b</kbd>)
- Format changes (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>=</kbd> <kbd>c</kbd>)
- Format selection (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>=</kbd> <kbd>s</kbd>)
- Format buffer with formatter (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>=</kbd> <kbd>B</kbd>)
- Format selection with formatter (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>=</kbd> <kbd>S</kbd>)

## Refactor
- Rename symbol (<kbd>SPC</kbd> <kbd>m</kbd> <kbd>r</kbd> <kbd>r</kbd>)

## Build and run
Bunch of MSBuild plus F# commands available under <kbd>SPC</kbd> <kbd>m</kbd> <kbd>c</kbd>

### CODE REVIEW

**Comment by sleepyfran** [comment]
Also created a PR to mention the required extensions in the docs: https://github.com/VSpaceCode/vspacecode.github.io/pull/37

**Comment by stevenguh** [comment]
Looks like a good start. It would be nice to have some [F# specific commands](https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L84-L455).

Btw, I didn't know the `kbd` is used to create those style. Updated the key binding doc generation script to use that instead :)

**Comment by sleepyfran** [comment]
Oh, completely missed those! Will add them in the next commit, thanks! 😄 

I was wondering why most of these commands that are general VSCode ones (like go to definition, go to error, etc.) are tied to a mode instead of being available in general since they're shared in between all modes? Is there any plan to move these out of the mode and just leaving it for language-specific things like the ones you sent?

**Comment by stevenguh** [comment]
> I was wondering why most of these commands that are general VSCode ones (like go to definition, go to error, etc.) are tied to a mode instead of being available in general since they're shared in between all modes? Is there any plan to move these out of the mode and just leaving it for language-specific things like the ones you sent?

Although, most language extensions implement most of the necessary parts to enable to built-in commands like format and go to definition, not all language extensions do. For example, `markdown` doesn't have go to definition, `clojure` has a specific commands of format at point. Ideally, it would be nice to be not to declare the bindings multiple times. The major mode is a conditioned on the language of the activate buffer. We are just keeping it simple until we figure some other ways to increase reuse.

**Comment by sleepyfran** [comment]
> > I was wondering why most of these commands that are general VSCode ones (like go to definition, go to error, etc.) are tied to a mode instead of being available in general since they're shared in between all modes? Is there any plan to move these out of the mode and just leaving it for language-specific things like the ones you sent?
> 
> Although, most language extensions implement most of the necessary parts to enable to built-in commands like format and go to definition, not all language extensions do. For example, `markdown` doesn't have go to definition, `clojure` has a specific commands of format at point. Ideally, it would be nice to be not to declare the bindings multiple times. The major mode is a conditioned on the language of the activate buffer. We are just keeping it simple until we figure some other ways to increase reuse.

Makes sense, thanks for the clarification! I'll add the keybindings you sent previously :)

**Comment by sleepyfran** [comment]
Added bindings for MSBuild and the REPL. Also want to add run project, do we have any convention for this? Maybe under <kbd>SPC</kbd><kbd>m</kbd><kbd>a</kbd><kbd>r</kbd>?

**Comment by stevenguh** [comment]
> Added bindings for MSBuild and the REPL, will update the description tomorrow.

Looking awesome!!

> do we have any convention for this? Maybe under <kbd>SPC</kbd><kbd>m</kbd><kbd>a</kbd><kbd>r</kbd>?

I am not sure either. I usually tried to look at existing/other major mode in spacemacs. We have a compile and test under <kbd>SPC</kbd><kbd>p</kbd> and run as debug or without debugging in <kbd>SPC</kbd><kbd>d</kbd>. Maybe under  <kbd>SPC</kbd><kbd>m</kbd><kbd>p</kbd>?

**Comment by stevenguh** [comment]
Some issues with the PR:
1. Why are there changes in `package-lock.json`?
2. Can you run `npm run sort-bindings` to ensure the bindings are all sorted?

**Comment by sleepyfran** [comment]
> Some issues with the PR:
> 
> 1. Why are there changes in `package-lock.json`?
> 2. Can you run `npm run sort-bindings` to ensure the bindings are all sorted?

Interestingly enough, those appeared after doing an install of the dependencies. I'll remove the change from the PR.

Sure! I'll also add the run under the section you mentioned.

**Comment by sleepyfran** [comment]
Done! Also ran the sorting of bindings which also affected other modes, hope that's okay, otherwise I can remove those specific changes.

**Comment by stevenguh** [comment]
I realized that as well, some of the current major mode bindings were not ordered correctly. I fixed it in f7bafb07849d810f7ebeb367ce81957985318267. Can you rebase your changes?

**Comment by stevenguh** [comment]
Otherwise, the changes seem alright. @MarcoIeni do you have time to check this out?

**Comment by MarcoIeni** [comment]
I will try to do it in the weekend. Sorry, a bit busy for now.

**Comment by MarcoIeni** [comment]
Thank you! 🚀

**Pull request merged**
