### PR TITLE
Add Go major mode

### PR DESCRIPTION
**Pull request by macintacos**
Ref: #98. Extracted from https://github.com/VSpaceCode/community-configs/pull/3

This is my "Go" major mode. I've been using it for about a week now and it feels pretty solid, but please let me know if you have any other critiques.

### CODE REVIEW

**Comment by stevenguh** [comment]
Awesome! It looks good, two follow up items. Can you 
- Update the CHANGELOG
- Add the go mode in our [doc](https://github.com/VSpaceCode/vspacecode.github.io/blob/master/docs/major-mode.md) and set PR to merge to `vspacecode-next` branch

Appreciate it!

**Comment by macintacos** [comment]
@stevenguh updated the CHANGELOG, and I'll go update the doc once this is merged. Note - as I was compiling the CHANGELOG, I made a few small changes:

- `SPC m a p w` is now `SPC m a w p` (makes more mnemonic sense)
- `SPC m b c` is now `SPC m b e` (makes more mnemonic sense)
- Removed `SPC m g E` since that was an external extension that probably doesn't matter to most users (Dash)

**Comment by stevenguh** [comment]
Thank you for contributing. I didn't expect you to list all the new go bindings in changelog, but that's cool too.

**Comment by macintacos** [comment]
Oh my bad - I did it for the Markdown mode so I figured it needed to be done for this one. Going forward if I contribute another large chunk I'll make it a bit smaller 😅

**Comment by stevenguh** [comment]
Appreciate the effort. It looks clear what's added :)

**Pull request merged**
