### PR TITLE
Add `<spc> T n` and `<spc> S n`

### PR DESCRIPTION
**Pull request by stevenguh**
We don't have any key bindings to enter into the notifications center. This PR add keys to toggle and show the notification center.

Some built-in behavior of the notification center:
- `j/k` and arrow keys can already be use directly with list (the `j/k` control is probably coming from vim's built-in bindings on list)
- `<esc>` can be used to close the view
- `cmd+backspace` can use to dismiss a notification on mac

### CODE REVIEW

**Comment by MarcoIeni** [comment]
I tried them and they work fine. I merged this, thanks!
Anyway, I still don't get why we use both `show` and `toggle` in a lot of actions.
Isn't toggle (`<spc> T n` in this case) enough?
When do you prefer to use `show` instead of `toggle`?

**Comment by stevenguh** [comment]
> Anyway, I still don't get why we use both show and toggle in a lot of actions.

haha I don't either 😅 This is probably happened when we merge the vim keybindings and bindings I had in the extension at the time. 

> When do you prefer to use show instead of toggle?
Toggle is most likely enough, since we also have the ability to do conditional bindings to toggle like `SPC f t`. I added the show command just because I found show and toggle command and they matched our menus.

I was thinking on consolidating the toggle and show menu somehow. I looked closely at the Show menu, and realized that spacemacs doesn't really equivalent concepts for what we have in the Show menu `SPC S`, which we are using it to change focus.

In spacemacs:
- UI toggle `SPC T` has a lot of setting-like keys to config the UI
- Toggle `SPC t` has a lot of the setting-like keys for buffer and editor

> Isn't toggle (<spc> T n in this case) enough?

Probably, to align the semantic of the menu in spacemacs I mentioned a above, maybe we should remove the notification toggle key in the UI toggle menu instead of removing the one in Show.

**Comment by MarcoIeni** [comment]
> maybe we should remove the notification toggle key in the UI toggle menu instead of removing the one in Show.

Yeah, I agree, `SPC T` should be for UI settings, not for opening windows.

So if you want I can remove `SPC T n` and replace the `SPC S n` action with `notifications.toggleList`

**Comment by stevenguh** [comment]
That would be awesome~~!! Thanks

**Comment by stevenguh** [comment]
Replaced `SPC S n` with `SPC T n`'s action, and removed `SPC T n` at 017ba42502920ad0513bd5dd24b1efea07855ce7

**Pull request merged**
