### PR TITLE
Add CUDA major mode

### PR DESCRIPTION
**Pull request by siboehm**
Adds CUDA major mode. It's a copy of C++ mode, plus an extra debugger feature.

I ran `npm run sort-bindings` like instructed by the PR template, seems like this was missing from the last few PRs since it's reformatted ALL THE CODE. I can drop that commit if you like.

### CODE REVIEW

**Comment by stevenguh** [comment]
Right, I think we have been forgetting to run `npm run sort-bindings` or automate that, I will run it again separately. Please drop that commit, it will make our review easier. Thanks :)

**Comment by siboehm** [comment]
done :)

**Comment by stevenguh** [comment]
Can you run `npm run format` because it is failing the format test. Thanks.

**Comment by stevenguh** [comment]
Thanks for contributing. Seems reasonable. Merged! @MarcoIeni Let me know if you see something out of place.

**Pull request merged**
