### PR TITLE
Order b (buffers...) bindings alphabetically (#121)

### PR DESCRIPTION
**Pull request by gnomesoup**
Per issues #121, I have alphabetized the "buffers..." bindings to be alphabetically and updated the CHANGELOG.

### CODE REVIEW

**Review by stevenguh — COMMENTED** [review]
I reviewed the change so far. None of the keys are missing after the change. Please update the CHANGELOG with the update on the `<spc> d`.

**Comment by gnomesoup** [comment]
I've updated the changelog. Do new pushes to the branch automatically show up here or do I need to do something to get them to show?

**Comment by gnomesoup** [comment]
I see that my later push shows below your other comment.

**Comment by stevenguh** [comment]
Congrats on the first time PR on this repo. I merged this so we can continue discuss how we move forward with https://github.com/VSpaceCode/VSpaceCode/issues/121#issuecomment-711658507

**Pull request merged**
