### PR TITLE
Major mode for Dart/Flutter

### PR DESCRIPTION
**Pull request by PatrickWulfe**
Added major mode bindings for Dart/Flutter
[https://github.com/VSpaceCode/VSpaceCode/issues/221](url)

### CODE REVIEW

**Comment by stevenguh** [comment]
That's pretty awesome!! I will spend some time next week looking over them. Just double checking have you run `npm run sort-bindings`

**Comment by PatrickWulfe** [comment]
Just ran it and pushed!

**Comment by stevenguh** [comment]
LGTM :) Can you update the CHANGLOG? And create another PR to our document site like https://github.com/VSpaceCode/vspacecode.github.io/pull/40?

**Comment by PatrickWulfe** [comment]
Done and done :D

**Pull request merged**
